# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MXRSNS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MXRSNS
  pod 'AFNetworking', '~>3.1.0'  

  target 'MXRSNSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MXRSNSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
